version: '3.8'

services:
  code-server:
    container_name: "code-server-a1l1q3-react-45"
    image: "sankarkg/level-three-test:latest"
    # image: "sankarkg/demo-test-one:latest"
    ports:
      - "8090:8080"
      - "5183:5173"
    volumes:
      - frontend-src-AON-46:/home/coder/project/src
    environment:
      - WATCHPACK_POLLING=true
      # - WATCHPACK_POLLING=true
      # - PUID=1000
      # - PGID=1000
      # - TZ=Etc/UTC
      # - CONNECTION_TOKEN=
    command:
        code-server --bind-addr 0.0.0.0:8080 --auth none /home/coder/project
    networks:
      - my_network

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "3005:80"
  #   depends_on:
  #     - code-server
      
      
networks:
  my_network:
    driver: bridge

volumes:
  frontend-src-AON-46:
    driver: local
 
# networks:
#   my_network:
#     driver: bridge
